#!/bin/sh
set -euf

getenv_or() {
    (env -0 | grep -zo -m 1 -P "^$1=\\K(.*)" || echo "$2") | tr -d '\000'
}

concurrency="$(getenv_or YT_CONCURRENCY 16)"
external_downloader="$(getenv_or YT_EXTERNAL_DOWNLOADER '--external-downloader aria2c')"
write_info_json="--write-info-json"
write_log_file=1
write_thumbnail="--write-thumbnail"
output_format="$(getenv_or YT_OUTPUT '[%(release_date,upload_date)s] %(title)s [%(channel)s] (%(id)s).%(ext)s')"

if [ $# -eq 0 ]; then
    cat 1>&2 <<EOF
Usage: $(basename "$0") [options] <yt-dlp arguments>

  --concurrency <value>     How many concurrent fragments/connections to use
  --no-aria2c               Don't use aria2c as an external downloader
  --no-info-json            Don't write info.json
  --no-log-file             Don't write log.txt
  --no-thumbnail            Don't write thumbnail
  --output|-o <format>      yt-dlp output template
EOF
    exit 1
fi

while :; do
    case "$1" in
        --concurrency)
            concurrency="$2"
            shift
            shift
            ;;
        --no-aria2c)
            external_downloader=""
            shift
            ;;
        --no-info-json)
            write_info_json=""
            shift
            ;;
        --no-log-file)
            write_log_file=0
            shift
            ;;
        --no-thumbnail)
            write_thumbnail=""
            shift
            ;;
        --output|-o)
            output_format="$2"
            shift
            shift
            ;;
        *)
            break;
    esac
done

log() {
    if [ "$write_log_file" = 1 ]; then
        tee log.txt
    else
        cat
    fi
}

yt-dlp -o "$output_format"                                                      \
    --parse-metadata "%(release_date,upload_date)s:%(date)s"                    \
    --parse-metadata "%(release_date,upload_date)s:%(meta_date)s"               \
    --concurrent-fragments "$concurrency"                                       \
    $external_downloader                                                        \
    --downloader-args aria2c:"-j $concurrency -x $concurrency -s $concurrency"  \
    $write_info_json                                                            \
    $write_thumbnail                                                            \
    --sub-langs all,-live_chat                                                  \
    --embed-chapters                                                            \
    --embed-metadata                                                            \
    --embed-subs                                                                \
    --embed-thumbnail                                                           \
    --compat-options no-attach-info-json                                        \
    "$@" 2>&1 | log

