#!/bin/sh
set -euf

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <json file> [ytarchive-raw options]" 1>&2;
    exit 1;
fi

json="$1"
shift

if [ ! -r "$json" ]; then
    echo "Unable to read file '$json'" 1>&2;
    exit 1;
fi

ytarchive-raw-go                                                    \
    --log-level debug                                               \
    --retries 30                                                    \
    --input "$json"                                                 \
    --output "[%(upload_date)s] %(title)s [%(channel)s] (%(id)s)"   \
    --threads 12                                                    \
    --temp-dir "yta_raw_temp"                                       \
    "$@" 2>&1 | tee log.txt

