#!/bin/sh
set -euf

if [ "$#" != 2 ]; then
    cat 1>&2 <<EOF
Usage: $(basename -- "$0") <input file> <video url/id>
EOF
    exit 1
fi

in="$1"
video="$2"

json="$(mktemp)"
mkv="$(mktemp --suffix=.mkv)"
thumb="$(mktemp --suffix=.jpg)"
trap "rm '$json' '$mkv' '$thumb'" EXIT

yt-dlp -j --skip-download --ignore-no-formats-error "$video" > "$json"

channel="$(jq -r .channel "$json")"
date="$(jq -r .upload_date "$json")"
desc="$(jq -r .description "$json")"
id="$(jq -r .id "$json")"
title="$(jq -r .title "$json")"

ext="$(basename -- "$in")"
ext="${ext##*.}"

clean() {
    echo "$@" | tr '<>:"/\|?*' '_'
}

out="[$date] $(clean "$title") [$(clean "$channel")] ($id).$ext"


wget "$(jq -r .thumbnail "$json")" -O "$thumb"

ffmpeg                                      \
    -i "$in"                                \
    -c copy                                 \
    -map_metadata -1                        \
    -metadata "title=$title"                \
    -metadata "comment=$desc"               \
    -metadata "author=$channel"             \
    -metadata "artist=$channel"             \
    -metadata "episode_id=$id"              \
    -attach "$thumb"                        \
    -metadata:s:t "mimetype=image/jpeg"     \
    -metadata:s:t "filename=thumbnail.jpg"  \
    -y                                      \
    "$mkv"
ffmpeg -i "$mkv" -c copy "$out"


